import type { Metadata } from 'next'
import { EB_Garamond } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './theme-provider'

const ebGaramondSans = EB_Garamond({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={ebGaramondSans.className}>
        <div className="noise-gradient"/>
        <ThemeProvider attribute="class" disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
